server:
  port: 8081

spring:
  #配置springData jap
  jpa:
    #指定是否在spring容器启动时创建表 默认是false
    generate-ddl: true
    #在控制台是否显示sql语句
    show-sql: true
    #指定应用重启后不重新更新表内容
    hibernate:
      ddl-auto: none

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.29.117.244:3306/cloudTest?useUnicode=true&characterEncoding=utf8
    username: root
    password: fuck123

  #指定当前微服务名称
  application:
    name: cloudstart-provider-depart

logging:
  level:
    root: info
    org.hibernate: info
    #在 showsql 为true的前提下显示sql中的动态插入值
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    #在 showsql 为true的前提下显示查询结果
    org.hibernate.hql.internal.ast.exec.BasicExecutor: trace
    com.couldstart: debug

#eureka:
#  client:
#    service-url:
#      #指定当前client所要连接的服务地址
#      defaultZone: http://localhost:8000/eureka
#  instance:
#    instance-id: cloudstart-provider-8081


info:
  auth: Reythor
  app.name: abcmsc
  company.name: www.kaikeba.com

eureka:
  client:
    # 指定区域名称
    region: xxx
    # 指定区域中所包含的地带zone
    availability-zones:
      xxx: kkb1,kkb2
    #指定各个地带zone中所包含的eureka server地址
    service-url:
      kkb1: http://localhost:8000/eureka
      kkb2: http://localhost:8000/eureka
      # 指定要连接的注册中心所在的区域
    fetch-remote-regions-registry: xxx